source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:Storie/pods.git'

# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'Demo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
#  pod 'distribute', :path => "../../"
    pod "StorieCloudSDK"

end
