# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  pod 'distribute', :path => "../../"
#  pod 'StorieVideo', :path => "../../storie-video-api-clients/storie-video-api-swift/"

end
